package com.sendkeep.app.util

import android.content.ClipData
import android.content.ClipDescription
import android.os.Build

object ClipboardSecurity {

    private val KNOWN_SENSITIVE_KEYS = listOf(
        "com.agilebits.onepassword",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "KeePassClipFormat",
        "com.bitwarden.concealed",
        "password",
        "concealed"
    )

    /**
     * Checks whether the given [ClipData] has been flagged as sensitive
     * (passwords, credit cards, 2FA tokens) by the OS or a password manager.
     */
    fun isSensitive(clip: ClipData?): Boolean {
        if (clip == null) return false
        val desc = clip.description ?: return false
        val extras = desc.extras ?: return false

        // Android 13+ (API 33) official platform sensitive flag
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            if (extras.getBoolean(ClipDescription.EXTRA_IS_SENSITIVE, false)) {
                return true
            }
        }

        // Backward compatibility key used prior to API 33
        if (extras.getBoolean("android.content.extra.IS_SENSITIVE", false)) {
            return true
        }

        // Check for recognized password manager / privacy flags
        for (key in KNOWN_SENSITIVE_KEYS) {
            if (extras.containsKey(key)) {
                return true
            }
        }

        return false
    }
}
